dist: focal
language: python
services: docker

before_install:
  - pip install -U pip wheel
  - docker-compose build
  - docker-compose up -d

script: docker-compose exec api python -m pytest "src/tests"
